### ISSUE TITLE
Sending image from google photos

### ISSUE THREAD

**Issue by Drac0n** [layerhq/Atlas-Android#52] opened 2016-02-12 16:03 UTC
Sending image from google photos that is not on device results in crash.

**Comment by sjones94549** [comment] 2016-02-23 21:37
Can you supply the crash details?  Preferably verbose logs, device version, and Android version.

**Comment by JeffRegan** [comment] 2016-03-24 01:23
Creating a file with a Uri other than a gallery Uri causes the crash.  It's in the `ThreePartImageUtils.java`.

`
public static Message newThreePartImageMessage(Context context, LayerClient layerClient, Uri imageUri) throws IOException
	{
		File imageFile = getImageFile(context, imageUri);
		return newThreePartImageMessage(context, layerClient, imageFile);
	}


private static File getCloudImageFile(Context context, Uri imageUri) throws FileNotFoundException
	{
		File f = new File(context.getCacheDir(), KTThreePartImageUtils.class.getSimpleName() + "." + System.nanoTime() + ".jpg");
		FileOutputStream fileOutStream = new FileOutputStream(f);

		InputStream inStream = context.getContentResolver().openInputStream(imageUri);
		Bitmap bitmap = BitmapFactory.decodeStream(inStream);
		bitmap.compress(Bitmap.CompressFormat.JPEG, 100, fileOutStream);
		return f;
	}

	private static File getImageFile(Context context, Uri imageUri) throws IOException
	{
		Cursor cursor = null;
		try
		{
			String[] projection = { MediaStore.Images.Media.DATA };
			cursor = context.getContentResolver().query(imageUri, projection, null, null, null);

			if (cursor == null || !cursor.moveToFirst() || !imageUri.getHost().equals("media"))
				return getCloudImageFile(context, imageUri);

			// can't get the image
			int columnIndex = cursor.getColumnIndexOrThrow(projection[0]);
			if (columnIndex < 0)
				return null;

			String path = cursor.getString(columnIndex);
			File f = new File(path);
			return f;
		}
		finally
		{
			if (cursor != null)
				cursor.close();
		}
	}
`

There's also a crash because the image is recycled too soon.  

`
previewBitmap.compress(Bitmap.CompressFormat.JPEG, PREVIEW_COMPRESSION_QUALITY, previewStream);
		previewBitmap.recycle();
		sampledBitmap.recycle();
		previewStream.close();
`
in the last constructor method fixes it

**Comment by JeffRegan** [comment] 2016-03-24 01:27
It's in `ThreePartImageUtils.java` and is caused whenever you select an image from a third party app (dropbox for example).  I'll try to remember to create a pull request.

**Comment by jindalbitazuga** [comment] 2016-07-14 12:06
Any updates on this issue Jeff, Sjones ?

**Comment by JeffRegan** [comment] 2016-07-18 16:24
I don't remember exactly what the error was, but this is the file I'm using.  Feel free to test it out, and if it works okay, I'm sure @sjones94549 wouldn't mind a pull request.

`public class KTThreePartImageUtils
{
	private static final String TAG = "KTThreePartImageUtils";

	//PROPERTIES
	//================================================================================
	public static final int ORIENTATION_0 = 0;
	public static final int ORIENTATION_180 = 1;
	public static final int ORIENTATION_90 = 2;
	public static final int ORIENTATION_270 = 3;

	public static final String MIME_TYPE_PREVIEW = "image/jpeg+preview";
	public static final String MIME_TYPE_INFO = "application/json+imageSize";

	public static final int PART_INDEX_FULL = 0;
	public static final int PART_INDEX_PREVIEW = 1;
	public static final int PART_INDEX_INFO = 2;

	public static final int PREVIEW_COMPRESSION_QUALITY = 75;
	public static final int PREVIEW_MAX_WIDTH = 512;
	public static final int PREVIEW_MAX_HEIGHT = 512;

	//MESSAGE PART HELPER
	//================================================================================
	public static MessagePart getInfoPart(Message message)
	{
		return message.getMessageParts().get(PART_INDEX_INFO);
	}
	public static MessagePart getPreviewPart(Message message)
	{
		return message.getMessageParts().get(PART_INDEX_PREVIEW);
	}
	public static MessagePart getFullPart(Message message)
	{
		return message.getMessageParts().get(PART_INDEX_FULL);
	}

	//LIFE CYCLE
	//================================================================================
	public static Message newThreePartImageMessage(Context context, LayerClient layerClient, Uri imageUri) throws IOException
	{
		File imageFile = getImageFile(context, imageUri);
		return newThreePartImageMessage(context, layerClient, imageFile);
	}

	public static Message newThreePartImageMessage(Context context, LayerClient layerClient, File imageFile) throws IOException
	{
		if (imageFile == null) throw new IllegalArgumentException("Null image file");
		if (!imageFile.exists()) throw new IllegalArgumentException("Image file does not exist");
		if (!imageFile.canRead()) throw new IllegalArgumentException("Cannot read image file");
		if (imageFile.length() <= 0) throw new IllegalArgumentException("Image file is empty");

		// Try parsing Exif data.
		int orientation = ORIENTATION_0;
		int exifOrientation = ExifInterface.ORIENTATION_UNDEFINED;
		try
		{
			ExifInterface exifInterface = new ExifInterface(imageFile.getAbsolutePath());
			exifOrientation = exifInterface.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_UNDEFINED);

			DebugLog.v(TAG, "Found Exif orientation: " + exifOrientation);

			switch (exifOrientation)
			{
				case ExifInterface.ORIENTATION_UNDEFINED:
				case ExifInterface.ORIENTATION_NORMAL:
				case ExifInterface.ORIENTATION_FLIP_HORIZONTAL:
					orientation = ORIENTATION_0;
					break;
				case ExifInterface.ORIENTATION_ROTATE_180:
				case ExifInterface.ORIENTATION_FLIP_VERTICAL:
					orientation = ORIENTATION_180;
					break;
				case ExifInterface.ORIENTATION_TRANSPOSE:
				case ExifInterface.ORIENTATION_ROTATE_90:
					orientation = ORIENTATION_270;
					break;
				case ExifInterface.ORIENTATION_TRANSVERSE:
				case ExifInterface.ORIENTATION_ROTATE_270:
					orientation = ORIENTATION_90;
					break;
			}
		}
		catch (IOException e)
		{
			DebugLog.e(TAG, e.toString());
		}

		return newThreePartImageMessage(context, layerClient, exifOrientation, orientation, imageFile);
	}

	/**
	 * Creates a new ThreePartImage Message.  The full image is attached untouched, while the
	 * preview is created from the full image by loading, resizing, and compressing.
	 *
	 * @param client
	 * @param file   Image file
	 * @return
	 */
	private static Message newThreePartImageMessage(Context context, LayerClient client, int exifOrientation, int orientation, File file) throws IOException
	{
		if (client == null) throw new IllegalArgumentException("Null LayerClient");
		if (file == null) throw new IllegalArgumentException("Null image file");
		if (!file.exists()) throw new IllegalArgumentException("No image file");
		if (!file.canRead()) throw new IllegalArgumentException("Cannot read image file");

		BitmapFactory.Options justBounds = new BitmapFactory.Options();
		justBounds.inJustDecodeBounds = true;
		BitmapFactory.decodeFile(file.getAbsolutePath(), justBounds);

		int fullWidth = justBounds.outWidth;
		int fullHeight = justBounds.outHeight;
		MessagePart full = client.newMessagePart("image/jpeg", new FileInputStream(file), file.length());

		boolean isSwap = orientation == ORIENTATION_270 || orientation == ORIENTATION_90;
		String intoString = "{\"orientation\":" + orientation + ", \"width\":" + (!isSwap ? fullWidth : fullHeight) + ", \"height\":" + (!isSwap ? fullHeight : fullWidth) + "}";
		MessagePart info = client.newMessagePart(MIME_TYPE_INFO, intoString.getBytes());
		DebugLog.v(TAG, "Creating image info: " + intoString);

		MessagePart preview;
		DebugLog.v(TAG, "Creating Preview from '" + file.getAbsolutePath() + "'");

		// Determine preview size
		int[] previewDim = Util.scaleDownInside(fullWidth, fullHeight, PREVIEW_MAX_WIDTH, PREVIEW_MAX_HEIGHT);
		DebugLog.v(TAG, "Preview size: " + previewDim[0] + "x" + previewDim[1]);

		// Determine sample size for preview
		int sampleSize = 1;
		int sampleWidth = fullWidth;
		int sampleHeight = fullHeight;
		while (sampleWidth > previewDim[0] && sampleHeight > previewDim[1])
		{
			sampleWidth >>= 1;
			sampleHeight >>= 1;
			sampleSize <<= 1;
		}

		if (sampleSize != 1)
			sampleSize >>= 1; // Back off 1 for scale-down instead of scale-up

		BitmapFactory.Options previewOptions = new BitmapFactory.Options();
		previewOptions.inSampleSize = sampleSize;

		DebugLog.v(TAG, "Preview sampled size: " + (sampleWidth << 1) + "x" + (sampleHeight << 1));

		// Create preview
		Bitmap sampledBitmap = BitmapFactory.decodeFile(file.getAbsolutePath(), previewOptions);
		Bitmap previewBitmap = Bitmap.createScaledBitmap(sampledBitmap, previewDim[0], previewDim[1], true);

		File temp = new File(context.getCacheDir(), KTThreePartImageUtils.class.getSimpleName() + "." + System.nanoTime() + ".jpg");
		FileOutputStream previewStream = new FileOutputStream(temp);
		DebugLog.v(TAG, "Compressing preview to '" + temp.getAbsolutePath() + "'");

		previewBitmap.compress(Bitmap.CompressFormat.JPEG, PREVIEW_COMPRESSION_QUALITY, previewStream);
		previewBitmap.recycle();
		sampledBitmap.recycle();
		previewStream.close();

		// Preserve exif orientation
		ExifInterface preserver = new ExifInterface(temp.getAbsolutePath());
		preserver.setAttribute(ExifInterface.TAG_ORIENTATION, Integer.toString(exifOrientation));
		preserver.saveAttributes();
		DebugLog.v(TAG, "Exif orientation preserved in preview");

		preview = client.newMessagePart(MIME_TYPE_PREVIEW, new FileInputStream(temp), temp.length());
		DebugLog.v(TAG, String.format(Locale.US, "Full image bytes: %d, preview bytes: %d, info bytes: %d", full.getSize(), preview.getSize(), info.getSize()));

		MessagePart[] parts = new MessagePart[3];
		parts[PART_INDEX_FULL] = full;
		parts[PART_INDEX_PREVIEW] = preview;
		parts[PART_INDEX_INFO] = info;
		return client.newMessage(parts);
	}

	private static File getCloudImageFile(Context context, Uri imageUri) throws FileNotFoundException
	{
		File f = new File(context.getCacheDir(), KTThreePartImageUtils.class.getSimpleName() + "." + System.nanoTime() + ".jpg");
		FileOutputStream fileOutStream = new FileOutputStream(f);

		InputStream inStream = context.getContentResolver().openInputStream(imageUri);
		Bitmap bitmap = BitmapFactory.decodeStream(inStream);
		bitmap.compress(Bitmap.CompressFormat.JPEG, 100, fileOutStream);
		return f;
	}

	private static File getImageFile(Context context, Uri imageUri) throws IOException
	{
		Cursor cursor = null;
		try
		{
			String[] projection = { MediaStore.Images.Media.DATA };
			cursor = context.getContentResolver().query(imageUri, projection, null, null, null);

			if (cursor == null || !cursor.moveToFirst() || !imageUri.getHost().equals("media"))
				return getCloudImageFile(context, imageUri);

			// can't get the image
			int columnIndex = cursor.getColumnIndexOrThrow(projection[0]);
			if (columnIndex < 0)
				return null;

			String path = cursor.getString(columnIndex);
			File f = new File(path);
			return f;
		}
		finally
		{
			if (cursor != null)
				cursor.close();
		}
	}
}`

**Comment by sriamar** [comment] 2016-08-24 20:49
Thanks, we will look at this, and hopefully can merge it soon.

**Comment by josealfonsomora** [comment] 2016-10-27 16:25
Hi @sriamar ! any update from this? Is fixed and merged?

I'm having a FileUriExposedException when I try to send a photo in a Nougat device:

```
Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.project.me/files/Pictures/cameraOutput1477575034574.jpg exposed beyond app through ClipData.Item.getUri()
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
       at android.net.Uri.checkFileUriExposed(Uri.java:2346)
       at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
       at android.app.Activity.startActivityForResult(Activity.java:4224)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
       at android.app.Activity.startActivityForResult(Activity.java:4183)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
       at com.layer.atlas.messagetypes.threepartimage.CameraSender.startCameraIntent(CameraSender.java:55)
       at com.layer.atlas.messagetypes.threepartimage.CameraSender.requestSend(CameraSender.java:63)
       at com.layer.atlas.AtlasMessageComposer$4.onClick(AtlasMessageComposer.java:319)
       at android.view.View.performClick(View.java:5609)
       at android.view.View$PerformClick.run(View.java:22262)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Thanks!

**Comment by smpete** [comment] 2016-10-27 23:47
Hi @josealfonsomora. We haven't had a chance to merge in the proposed fix yet. I should have some time in the coming weeks to take a look at this. Currently looking at high priority authentication issues in our SDK. I'll keep you posted.

**Comment by Dan2anderson** [comment] 2016-12-09 17:45
We are seeing a similar issue in Nougat 
We are on layer-sdk:0.23.2   
Atlas Version 0.3.1

when users use the Camera feature to to take a picture to send in a message.  When you tap on the "Camera" option the app crashes immediately with an android.os.FileUriExposedException.   which appears to be caused by not using the new FileProvider instead of the File class.  

full stack trace :
`FATAL EXCEPTION: main
Process: com.salesrabbit.android.sales.universal, PID: 25090
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.salesrabbit.android.sales.universal/files/Pictures/cameraOutput1481305062027.jpg exposed beyond app through ClipData.Item.getUri()
    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
    at android.net.Uri.checkFileUriExposed(Uri.java:2346)
    at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
    at android.app.Activity.startActivityForResult(Activity.java:4224)
    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
    at android.app.Activity.startActivityForResult(Activity.java:4183)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
    at com.layer.atlas.messagetypes.threepartimage.CameraSender.startCameraIntent(CameraSender.java:55)
    at com.layer.atlas.messagetypes.threepartimage.CameraSender.requestSend(CameraSender.java:63)
    at com.layer.atlas.AtlasMessageComposer$4.onClick(AtlasMessageComposer.java:335)
    at android.view.View.performClick(View.java:5609)
    at android.view.View$PerformClick.run(View.java:22259)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by thecombatwombat** [comment] 2017-05-16 18:00
@Dan2anderson This issue should be fixed in Atlas a while back. Could you tell me what version you're on, and if not the latest, perhaps give that a try?

**Comment by thecombatwombat** [comment] 2017-05-17 23:10
@Dan2anderson I'm reasonably certain the matter is resolved, and I'm closing this ticket. 

Please get back to us in case you're still experiencing a problem.

**Closed by thecombatwombat** 2017-05-17 23:10 UTC
