### ISSUE TITLE
Images in Messages List

### ISSUE THREAD

**Issue by JeffRegan** [layerhq/Atlas-Android#65] opened 2016-04-11 21:37 UTC
The messages adapter uses the recyclerview height to calculate the height of images.  Since opening and closing the keyboard changes the recyclerview's height, images will change size based on whether or not the keyboard is up.  Most notably, if you send text right after sending an image, the previous image will shrink.

**Comment by sriamar** [comment] 2017-05-15 20:30
PR : https://github.com/layerhq/Atlas-Android/pull/182

**Comment by thecombatwombat** [comment] 2017-05-16 17:56
Duplicate of issue #135 , which is tracked by #182. Closing this issue.

**Closed by thecombatwombat** 2017-05-16 17:56 UTC
